### ISSUE TITLE
Can't handle &nbsp;

### ISSUE THREAD

**Issue by loentar** [peterbe/premailer#100]
If source html contain `&nbsp;` exception will thrown:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/premailer/__main__.py", line 133, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/premailer/__main__.py", line 128, in main
    options.outfile.write(p.transform())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 45: ordinal not in range(128)
```

Test html:

```
<html>
  <body>&nbsp;</body>
</html>
```

**Comment by peterbe** [comment]
I started writing a unit test to reproduce this. So I wrote this:

```python
    def test_nbsp_only(self):
        html = """
        <html>
          <body>&nbsp;</body>
        </html>
        """
        p = Premailer(html)
        p.transform()
```

It didn't fail. 

Any other ideas of how to reproduce this?

**Comment by kengruven** [comment]
The Python Premailer class supports "&nbsp;", but as part of its transformation, it converts it to the character U+00A0 (or maybe the UTF-8 bytes C2 A0).

If you run it in Python to convert a string to a string (in memory), it works.  If you run it via the command-line using premailer/__main__.py, it fails:

    python -m premailer --file /tmp/nbsp.html --output /tmp/nbsp-pm.html
    (traceback...then:)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 29: ordinal not in range(128)

It looks like the output file is being created with an ASCII-only codec.

**Comment by peterbe** [comment]
What does that `/tmp/nbsp.html` look like? E.g. if you do:
```python
>>> import codecs
>>> codecs.open('/tmp/nbsp.html', 'r', 'utf-8').read()
```

**Comment by kengruven** [comment]
It's plain ASCII.  It's the "Test html" snippet from loentar's original issue, at top.

Running your command with Python 2.7 gives me:

    u'<html>\n  <body>&nbsp;</body>\n</html>\n'

**Comment by peterbe** [comment]
So then I wonder if it's something to do with the way the `__main__.py` module **writes** the HTML back. As you can see in my comment above, I was able to run the transform function on that same input. Strange.

**Comment by kengruven** [comment]
Yes, argparse.FileType creates a file with open(), which in Python 2.7 uses ASCII encoding by default.

[In Python 3.4](https://bugs.python.org/issue11175), argparse.FileType [supports the encoding= keyword argument](https://docs.python.org/3/library/argparse.html#filetype-objects), but in Python 2.7, it always uses the default encoding, which is ASCII.

If you want to maintain support for Python 2.x with the command-line tool, and you don't want to backport argparse.FileType from Python 3.4, then perhaps the simplest thing to do would be to run parser.parse_args(...) as now, but then after that do something like:

    if options.outfile is not sys.stdout:
        options.outfile.close()
        options.outfile = codecs.open(options.outfile.name, 'w', encoding='UTF-8')

**Comment by peterbe** [comment]
Cool. I think I understand it but if you make a pull request I'll take a closer look.

**Comment by OrangeDog** [comment]
Correct me if I'm wrong but there are two issues here.

1. Entities aren't preserved and are converted to Unicode.
2. Unicode can't be written to file - #152 

Is anyone addressing the first one?
