### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by goors** [peterbe/premailer#102]
This thing is great but it is not working for like 98% of my html pages (html emails).
I ma getting lot of errors and all of them are like:

<pre>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15052: ordinal not in range(128)
</pre>

Any idea how to solve this?

**Comment by peterbe** [comment]
I suspect it's a problem **outside** of `premailer`. That you send in a byte string that contains non-ascii characters. 
See this for example:
```python
>>> import premailer
>>> p=premailer.Premailer('<html>\xa3</html>')
>>> p.transform()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "premailer/premailer.py", line 296, in transform
    root = tree if stripped.startswith(tree.docinfo.doctype) else page
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa3 in position 6: ordinal not in range(128)

>>> # BUT!
>>> p=premailer.Premailer(u'<html>\xa3</html>')  # notice the prefix u
>>> p.transform()
u'<html>\n<head></head>\n<body><p>\xa3</p></body>\n</html>\n'
```

**Comment by goors** [comment]
Take a look for example:

<pre>
p=premailer.Premailer(u'<html>\xa0</html>')

UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 30: ordinal not in range(128)
</pre>

**Comment by peterbe** [comment]
What version of python are you using?

```python
>>> import premailer
>>> premailer.__version__
u'2.8.1'
>>> premailer.Premailer(u'\xa0')
<premailer.premailer.Premailer object at 0x10632ab90>
>>> p=premailer.Premailer(u'\xa0')
>>> p.transform()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "premailer/premailer.py", line 292, in transform
    tree = etree.fromstring(stripped, parser).getroottree()
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102470)
  File "parser.pxi", line 1667, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101229)
  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96139)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92476)
  File "parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91939)
lxml.etree.XMLSyntaxError: None
```

**Comment by goors** [comment]
I am using 2.7.6.

**Comment by peterbe** [comment]
So am I. Hm...

Perhaps you're using a really old version of `premailer`. 

Try to copy and paste the steps I did in the comment just above.

**Comment by goors** [comment]
I am using latest premailer.

**Comment by goors** [comment]
Here is output:

<pre>
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import premailer
>>> premailer.__version__
u'2.8.1'
>>> p=premailer.Premailer(u'\xa0')
>>> p.transform()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/premailer-2.8.1-py2.7.egg/premailer/premailer.py", line 292, in transform
    tree = etree.fromstring(stripped, parser).getroottree()
  File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70691)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106689)
  File "parser.pxi", line 1709, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105390)
  File "parser.pxi", line 1047, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:99763)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94543)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:96003)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95262)
lxml.etree.XMLSyntaxError: None

</pre>

**Comment by peterbe** [comment]
Cool. So it's as expected. Not a bug in premailer.

**Comment by anggiaj** [comment]
So how to resolve this issue?

**Comment by peterbe** [comment]
> So how to resolve this issue?

@anggiaj Make sure you send in a string that is valid XML (or valid HTML).
