### ISSUE TITLE
SyntaxErr on <h1> with !important

### ISSUE THREAD

**Issue by pzelnip** [peterbe/premailer#133]
Feeding the following into ```transform()``` results in a ```SyntaxErr```:

```
<style type="text/css">
h1 { border:1px solid black }
p { color:red;}
</style>
<p>Hey</p>
<h1 style="display: block;font-family: Helvetica;font-size: 26px;font-style: normal;font-weight: bold;line-height: 100%;letter-spacing: normal;margin-top: 0;margin-right: 0;margin-bottom: 10px;margin-left: 0;text-align: left;color: #202020 !important;">Some Stuff</h1>
```

Results in:

```
SyntaxErr: PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): ('CHAR', '!', 1, 230)
```

Removing the ```!important``` from the inline style on the H1 allows it to be inlined as expected.

**Comment by peterbe** [comment]
`SyntaxErr` is a strange name. Either way, I guess it sort of strangely makes sense because you're not supposed to have an `!important` on an inline style tag, because it makes no sense having it there. 

Can you share what the whole traceback is?

**Comment by pzelnip** [comment]
```
>>> transform(html)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/premailer/premailer.py", line 571, in transform
    return Premailer(html, base_url=base_url).transform()
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/premailer/premailer.py", line 398, in transform
    element['style'], element['classes'])
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/premailer/merge_style.py", line 52, in merge_styles
    for k, v in csstext_to_pairs(inline_style):
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/premailer/merge_style.py", line 13, in csstext_to_pairs
    parsed = cssutils.css.CSSVariablesDeclaration(csstext)
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/cssutils/css/cssvariablesdeclaration.py", line 47, in __init__
    self.cssText = cssText
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/cssutils/css/cssvariablesdeclaration.py", line 154, in _setCssText
    emptyOk=True)
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/cssutils/prodparser.py", line 573, in parse
    type_, val = prod.toSeq(token, tokens)
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/cssutils/css/cssvariablesdeclaration.py", line 136, in <lambda>
    parent=self)
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/cssutils/css/value.py", line 57, in __init__
    self.cssText = cssText
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/cssutils/css/value.py", line 173, in _setCssText
    prods)
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/cssutils/prodparser.py", line 562, in parse
    self._log.error(u'%s: %s: %r' % (name, e, token))
  File "/Users/aparkin/.envs/premailer/lib/python2.7/site-packages/cssutils/errorhandler.py", line 98, in __handle
    raise error(msg)
xml.dom.SyntaxErr: PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): ('CHAR', '!', 1, 230)
```

**Comment by peterbe** [comment]
Why do you have a `!important` inside a inline style attribute?
If `cssutils` can't allow it I'm not sure premailer should allow it either. They're pretty tightly linked. 
What do you think?
A hack would be to do a string replace of all `!important` strings if they come from an inline attribute.

**Comment by peterbe** [comment]
Or does this have nothing to do with it being in an inline style attribute? Is it simply a problem with `!important` being at play?

**Comment by pzelnip** [comment]
```!important``` was in the inline style as this was a template inherited from another source that I don't have control over.  I agree it's superflous and my current workaround is to just manually remove it before inlining.

It does look though like it's a cssutils exception propagating up, would it be worth having a try/catch around the call to ```cssutils.css.CSSVariablesDeclaration``` in ```merge_style.py```

**Comment by lavr** [comment]
Hi!

Same issue with ```!important```. It looks like critical issue because I have no control over user loaded html and I can not just say ```Oh snap! SyntaxErr``` ))

Here is abstract sample html code and traceback:

    >>> from premailer import transform
    >>> transform("""<style>tag{prop: value1;}</style><tag style="prop: value2 !important;"/>""")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File ".env/lib/python2.7/site-packages/premailer/premailer.py", line 571, in transform
        return Premailer(html, base_url=base_url).transform()
      File ".env/lib/python2.7/site-packages/premailer/premailer.py", line 398, in transform
        element['style'], element['classes'])
      File ".env/lib/python2.7/site-packages/premailer/merge_style.py", line 52, in merge_styles
        for k, v in csstext_to_pairs(inline_style):
      File ".env/lib/python2.7/site-packages/premailer/merge_style.py", line 13, in csstext_to_pairs
        parsed = cssutils.css.CSSVariablesDeclaration(csstext)
      File ".env/lib/python2.7/site-packages/cssutils/css/cssvariablesdeclaration.py", line 47, in __init__
        self.cssText = cssText
      File ".env/lib/python2.7/site-packages/cssutils/css/cssvariablesdeclaration.py", line 154, in _setCssText
        emptyOk=True)
      File ".env/lib/python2.7/site-packages/cssutils/prodparser.py", line 573, in parse
        type_, val = prod.toSeq(token, tokens)
      File ".env/lib/python2.7/site-packages/cssutils/css/cssvariablesdeclaration.py", line 136, in <lambda>
        parent=self)
      File ".env/lib/python2.7/site-packages/cssutils/css/value.py", line 57, in __init__
        self.cssText = cssText
      File ".env/lib/python2.7/site-packages/cssutils/css/value.py", line 173, in _setCssText
        prods)
      File ".env/lib/python2.7/site-packages/cssutils/prodparser.py", line 562, in parse
        self._log.error(u'%s: %s: %r' % (name, e, token))
      File ".env/lib/python2.7/site-packages/cssutils/errorhandler.py", line 98, in __handle
        raise error(msg)
    xml.dom.SyntaxErr: PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): ('CHAR', '!', 1, 14)

Any ideas how to fix this ?

**Comment by lavr** [comment]
I'm not big fun of ```!important``` rule but some say it is necessary in some case on some mail clients i.e. Gmail

**Comment by elidickinson** [comment]
`!important` in a `<style>` block has perfectly legitimate uses. But inside a `<tag style="...">` style attribute, I think it has no effect and is not valid HTML/CSS.

**Comment by peterbe** [comment]
What @elidickinson said.

**Comment by peterbe** [comment]
Basically, putting `!important` in an inline style doesn't make sense because nothing is more important than inline styles already.

**Comment by lavr** [comment]
I'm sure you're right about nonimportance of this rule.
But I have html from real designer with bunch of ``important`` rules.
Even if he is wrong, I should not show "xml.dom.SyntaxErr" error in my app.

Let's fix this please

**Comment by peterbe** [comment]
I understand that, but perhaps a better approach would be to first de-break the HTML by doing a search-and-replace of all `\s*!important` things from the style attributes. What do you think?

**Comment by lavr** [comment]
Please take a look at pull request and say If you see any caveats.

I want to test this approach for a while on my systems.

**Comment by peterbe** [comment]
I'm confused. https://github.com/peterbe/premailer/pull/138 is about being able to cope with CSS blocks like `inline = '{color:pink} :hover{color:purple} :active{color:red}'`. 
But this issue is about coping with the presence of a `!important` in the CSS block.

**Comment by lavr** [comment]
I remove test with  ```{color:pink} :hover{color:purple} :active{color:red}```  because it does not raise exception any more.

**Comment by lavr** [comment]
I agree it may be confused. 
Test is back, but with some changes.

**Comment by lavr** [comment]
#138 seems to be less confusing now

**Comment by peterbe** [comment]
For your information, Gmail does need `!important` for certain things such as `display:none`. But that apparently breaks Outlook: https://github.com/peterbe/premailer/issues/150

**Comment by cthedot** [comment]
> Basically, putting !important in an inline style doesn't make sense because nothing is more important than inline styles already.

Sorry, not true. See http://jsbin.com/vurufej/edit?html,css,output

Stylesheet !imporant overwrites inline style attributes and only if these are !important too cannot be overwritten.

**Comment by elidickinson** [comment]
That may happen to work in some browsers, but is it to the spec? I'm under
the impression it is not technically valid HTML/CSS...

Regardless you probably don't ever want to use inline !important in emails:
https://www.campaignmonitor.com/blog/email-marketing/2010/05/outlook-2007-and-the-inline-important-declaration/
