### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by oldo** [peterbe/premailer#152]
Hi Peter,
I've created an html document with bootstrap styling and when I try and run Premailer from the CLI I get the following error:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/oldo/Python/virtual-environments/AMS-Journal/lib/python2.7/site-packages/premailer/__main__.py", line 142, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/oldo/Python/virtual-environments/AMS-Journal/lib/python2.7/site-packages/premailer/__main__.py", line 137, in main
    options.outfile.write(p.transform(pretty_print=options.pretty))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 106688: ordinal not in range(128)
```
I have tried everything that I can think of to try and avoid this, but can't seem to make any progress. What would usually cause this error and do you know a way to fix it?
Thanks!

**Comment by oldo** [comment]
I was finally able to find a workaround to avoid this error :-)
Please [see here](http://stackoverflow.com/questions/34681040/premailer-unicodeencodeerror-ascii-codec-cant-encode-character-u-u2013-i/34691698#34691698) if you are interested.

**Comment by peterbe** [comment]
How do you even reproduce this error?
premailer has a pretty extensive set of unit tests and they cover much unicode handling stuff. 

A lot of times, the reason you get into UnicodeEncodeError is because of something going wrong *before* you use the library or third-party function that is raising the error. For example, in python 2:
```python
>>> def foo(add):
...     return u'a' + add
...
>>>
```
Seems sensible, right? It adds the (unicode) character `a` to the start of whatever you put in:
```python
inp = 'ä'
>>> foo(inp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in foo
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```
What happened here is that it was a mistake to define the variable `inp` as a byte string when it contained non-ascii characters. 

This is just an example of a problem I often see. But I would encourage you to evaluate what you're sending in to premailer and check that it's sane. If not, we might have a bug on our hands. 

Also, that line `options.outfile.write(p.transform(pretty_print=options.pretty))` is problematic because it's hard to see where the error is happening. But it's the `options.outfile.write()` not the `p.transform(pretty_print=pretty_print)` because otherwise the traceback would talk about other lines I think. 
You could, in your case, break open that and do something like this (temporarily):
```python
transformed = p.transform(pretty_print=options.pretty)
print repr(transformed)
print type(transformed)
options.outfile.write(transformed)
```

That'd give us more insight into what's going on.

**Comment by peterbe** [comment]
@oldo See https://github.com/peterbe/premailer/pull/142
Perhaps you can help there.

**Comment by kengruven** [comment]
This looks just like #100.

I have a PR for that but I never got around to rebasing and adding tests -- admittedly, two of my weaknesses.  Help would be much appreciated.

**Comment by OrangeDog** [comment]
If you're still looking for a reproduction, here's a trivial one.

    echo "&nbsp;" | python -m premailer --output out.html

**Comment by dAnjou** [comment]
I was running into a similar issue:

```
❯ git diff master staging | sh ~/Downloads/ansi2html.sh | python -m premailer > /tmp/diff.html          
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/max/.local/lib/python2.7/site-packages/premailer/__main__.py", line 148, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/max/.local/lib/python2.7/site-packages/premailer/__main__.py", line 143, in main
    options.outfile.write(p.transform(pretty_print=options.pretty))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 126700: ordinal not in range(128)
```

https://github.com/pixelb/scripts/blob/4d075026866dff074749f938c111c7a0478309c1/scripts/ansi2html.sh

Found this article http://chase-seibert.github.io/blog/2014/01/12/python-unicode-console-output.html and the following command worked:

```
git diff master staging | sh ~/Downloads/ansi2html.sh | PYTHONIOENCODING=UTF-8 python -m premailer > /tmp/diff.html
```

**Comment by peterbe** [comment]
If `premailer` reads in from `sys.stdin` and the stream isn't unicode, it ought to be assumed to be UTF-8 and automatically converted to Unicode. 
The only question is, how do we write a great unit test that works in both py2 and py3 :)
Any takers?

**Comment by nrlakin** [comment]
I am having a similar issue; I get the UnicodeEncodeError when I try the command line approach. If I run the transform function in a Python shell, I can see that it's replacing "&deg" in my input HTML with "\xb0", the UTF-8 degree sign. Isn't this behavior undesired? It seems like it should leave ampersand-escaped special characters in HTML alone.

**Comment by peterbe** [comment]
@nrlakin What version of Python?

**Comment by nrlakin** [comment]
Python 2.7.10, premailer 3.0.1. It looks like you need to use the -o option to get the bug; if I omit the -o, it prints the output to stdout, with the degree sign rendered as unicode. Here's a simple script to reproduce:

```
echo "<html><body><p>&deg;</p></body></html>" > test.html
python -m premailer -f test.html -o out.html
```

When I run that, I get the exception.
