### ISSUE TITLE
Transforming documents containing unicode

### ISSUE THREAD

**Issue by Sertion** [peterbe/premailer#69]
I get the following issue when parsing a file containing, for example, Japanese characters:

```
albin@dev:~/premailer-tests$ python -m premailer --file t.html
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/premailer-2.1.1-py2.7.egg/premailer/__main__.py", line 119, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/premailer-2.1.1-py2.7.egg/premailer/__main__.py", line 114, in main
    options.outfile.write(p.transform())
  File "/usr/local/lib/python2.7/dist-packages/premailer-2.1.1-py2.7.egg/premailer/premailer.py", line 213, in transform
    root = tree if stripped.startswith(tree.docinfo.doctype) else page
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 216: ordinal not in range(128)
```

test.html has the following content:

``` html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Unicode Test</title>
    <style>
        h1 {
            font-family: 'Gulim', sans-serif;
        }
    </style>
</head>
<body>
    <h1>問題</h1>
</body>
</html>
```

I am running the [latest files](https://github.com/peterbe/premailer/tree/8b2b8a706e9ded16c7c0358320a528adcb9c8c45) and installed using the `python setup.py install`.

**Comment by jfernstad** [comment]
Still seeing Unicode issues in v2.9.6, this time it's UnicodeEncodeError. 

python -m premailer --base-url=http://google.com/ -f input.html -o output.html

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./venv/lib/python2.7/site-packages/premailer/__main__.py", line 142, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./venv/lib/python2.7/site-packages/premailer/__main__.py", line 137, in main
    options.outfile.write(p.transform(pretty_print=options.pretty))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 13362: ordinal not in range(128)

**Comment by jfernstad** [comment]
To add some more information, this happens in HTML files using &nbsp; somewhere. The parser probably converts this to the 0xA0 'NO-BREAK SPACE' character, breaking the encoding process.

**Comment by nrlakin** [comment]
Is there a solution for this issue? I'm having the same problem--my HTML has a "&deg" character.
